услуги:
  - тип: статический
 имя: пва-ад-сервис
 buildCommand: "
 опубликоватьДир: .
 заголовки:
      - путь: "*.html"
 имя: Тип контента
 стоимость: текст/html
      - путь: "*.css"
 имя: Тип контента
 стоимость: текст/css
      - путь: "*.js"
 имя: Тип контента
 стоимость: приложение/javascript
